version: '3'

services:
  # MongoDB database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Web App
  web-app:
    build: ./web_app
    container_name: web-app
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: